package org.laidu.blog.mapper;

import org.laidu.blog.domain.Post;
import org.laidu.blog.domain.PostWithBLOBs;

import java.util.List;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int insert(PostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int insertSelective(PostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    PostWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int updateByPrimaryKeySelective(PostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(PostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int updateByPrimaryKey(Post record);

    List<PostWithBLOBs> getPostListByTermId(long termId);

    List<PostWithBLOBs> getAllPostList();

    List<PostWithBLOBs> getPostListByDate();

    List<PostWithBLOBs> getLastPost(long count);
}