package org.laidu.blog.mapper;

import org.laidu.blog.domain.Term;
import org.laidu.blog.domain.TermParent;

import java.util.List;

public interface TermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int deleteByPrimaryKey(Long termId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int insert(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int insertSelective(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    Term selectByPrimaryKey(Long termId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int updateByPrimaryKeySelective(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int updateByPrimaryKey(Term record);

    List<TermParent> getParentNav();

    List<Term> getChildrenNavByPerentId(Long termId);

    List<TermParent> getParentTerm();

    List<Term> getChildrenTermByPerentId(Long termId);
}