package org.laidu.blog.mapper;

import org.laidu.blog.domain.Term;
import org.laidu.blog.domain.TermParent;
import org.laidu.blog.domain.Terms_taxonomy;

import java.util.List;

public interface Terms_taxonomyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_taxonomy
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int deleteByPrimaryKey(Long termTaxonomyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_taxonomy
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int insert(Terms_taxonomy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_taxonomy
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int insertSelective(Terms_taxonomy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_taxonomy
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    Terms_taxonomy selectByPrimaryKey(Long termTaxonomyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_taxonomy
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int updateByPrimaryKeySelective(Terms_taxonomy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_taxonomy
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Terms_taxonomy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term_taxonomy
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    int updateByPrimaryKey(Terms_taxonomy record);

    List<TermParent> getParentNav();

    List<Term> getChildrenNav();

    List<TermParent> getAllterm();
}