package org.laidu.blog.domain;

public class CommentWithBLOBs extends Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_author
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String commentAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_content
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_author
     *
     * @return the value of comments.comment_author
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getCommentAuthor() {
        return commentAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_author
     *
     * @param commentAuthor the value for comments.comment_author
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setCommentAuthor(String commentAuthor) {
        this.commentAuthor = commentAuthor == null ? null : commentAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_content
     *
     * @return the value of comments.comment_content
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_content
     *
     * @param commentContent the value for comments.comment_content
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }
}