package org.laidu.blog.domain;

public class PostWithBLOBs extends Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.post_content
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String postContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.post_title
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String postTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.post_excerpt
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String postExcerpt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.to_ping
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String toPing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.pinged
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String pinged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.post_content_filtered
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String postContentFiltered;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.post_content
     *
     * @return the value of posts.post_content
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getPostContent() {
        return postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.post_content
     *
     * @param postContent the value for posts.post_content
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent == null ? null : postContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.post_title
     *
     * @return the value of posts.post_title
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.post_title
     *
     * @param postTitle the value for posts.post_title
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle == null ? null : postTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.post_excerpt
     *
     * @return the value of posts.post_excerpt
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getPostExcerpt() {
        return postExcerpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.post_excerpt
     *
     * @param postExcerpt the value for posts.post_excerpt
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setPostExcerpt(String postExcerpt) {
        this.postExcerpt = postExcerpt == null ? null : postExcerpt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.to_ping
     *
     * @return the value of posts.to_ping
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getToPing() {
        return toPing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.to_ping
     *
     * @param toPing the value for posts.to_ping
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setToPing(String toPing) {
        this.toPing = toPing == null ? null : toPing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.pinged
     *
     * @return the value of posts.pinged
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getPinged() {
        return pinged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.pinged
     *
     * @param pinged the value for posts.pinged
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setPinged(String pinged) {
        this.pinged = pinged == null ? null : pinged.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.post_content_filtered
     *
     * @return the value of posts.post_content_filtered
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getPostContentFiltered() {
        return postContentFiltered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.post_content_filtered
     *
     * @param postContentFiltered the value for posts.post_content_filtered
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setPostContentFiltered(String postContentFiltered) {
        this.postContentFiltered = postContentFiltered == null ? null : postContentFiltered.trim();
    }
}