package org.laidu.blog.domain;

public class Term {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terms.term_id
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private Long termId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terms.name
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terms.slug
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String slug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terms.term_group
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private Long termGroup;

    private Long count;

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terms.term_id
     *
     * @return the value of terms.term_id
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public Long getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terms.term_id
     *
     * @param termId the value for terms.term_id
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setTermId(Long termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terms.name
     *
     * @return the value of terms.name
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terms.name
     *
     * @param name the value for terms.name
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terms.slug
     *
     * @return the value of terms.slug
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terms.slug
     *
     * @param slug the value for terms.slug
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setSlug(String slug) {
        this.slug = slug == null ? null : slug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terms.term_group
     *
     * @return the value of terms.term_group
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public Long getTermGroup() {
        return termGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terms.term_group
     *
     * @param termGroup the value for terms.term_group
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setTermGroup(Long termGroup) {
        this.termGroup = termGroup;
    }
}