package org.laidu.blog.domain;

import java.util.List;

public class Terms_taxonomy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_taxonomy.term_taxonomy_id
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private Long termTaxonomyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_taxonomy.term_id
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private Long termId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_taxonomy.taxonomy
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String taxonomy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_taxonomy.parent
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private Long parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_taxonomy.count
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private Long count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term_taxonomy.description
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_taxonomy.term_taxonomy_id
     *
     * @return the value of term_taxonomy.term_taxonomy_id
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public Long getTermTaxonomyId() {
        return termTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_taxonomy.term_taxonomy_id
     *
     * @param termTaxonomyId the value for term_taxonomy.term_taxonomy_id
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setTermTaxonomyId(Long termTaxonomyId) {
        this.termTaxonomyId = termTaxonomyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_taxonomy.term_id
     *
     * @return the value of term_taxonomy.term_id
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public Long getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_taxonomy.term_id
     *
     * @param termId the value for term_taxonomy.term_id
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setTermId(Long termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_taxonomy.taxonomy
     *
     * @return the value of term_taxonomy.taxonomy
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getTaxonomy() {
        return taxonomy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_taxonomy.taxonomy
     *
     * @param taxonomy the value for term_taxonomy.taxonomy
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setTaxonomy(String taxonomy) {
        this.taxonomy = taxonomy == null ? null : taxonomy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_taxonomy.parent
     *
     * @return the value of term_taxonomy.parent
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public Long getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_taxonomy.parent
     *
     * @param parent the value for term_taxonomy.parent
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setParent(Long parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_taxonomy.count
     *
     * @return the value of term_taxonomy.count
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_taxonomy.count
     *
     * @param count the value for term_taxonomy.count
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term_taxonomy.description
     *
     * @return the value of term_taxonomy.description
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term_taxonomy.description
     *
     * @param description the value for term_taxonomy.description
     *
     * @mbg.generated Fri Sep 09 09:11:24 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}